### ISSUE TITLE
How can I combine the header item with the item to be an item?thanks,while i scrolling,the position is section,i want the position is the current section with  the current section's header's item,not is only section

### ISSUE THREAD

**Issue by ZuJunJun** [truizlop/SectionedRecyclerView#27] opened 2018-06-28 10:56 UTC

**Comment by truizlop** [comment] 2018-06-28 12:05
First of all, this is not a very appropriate way of reporting an issue. You are writint everything in the title and provide no description about the problem and how to reproduce it; and even with that, it is quite difficult to guess what your actual issue is. Moreover, the problem I assume you have is already explained in the documentation of the library.

Since this is not an issue with the library but your use case problem, and the usage of the library is already documented in the README, I'm closing this.

**Closed as completed by truizlop** 2018-06-28 12:05 UTC
